### PR TITLE
Various fixes, improvements and optimizations

### PR DESCRIPTION
**Pull request by JustKappaMan**
Hi. See commit messages for details :smile:

### CODE REVIEW

**Comment by JustKappaMan** [comment]
@mdiller hey, could you either merge or close the PR? :)

**Comment by mdiller** [comment]
Apologies! I haven't been checking my github notifications haha. I'd like to keep tabs for my indentation. Could you update the PR to fix that back to how it was?

**Comment by JustKappaMan** [comment]
@mdiller sure, done

**Comment by mdiller** [comment]
Ok cool! Now that i can see the changes, this looks good! The last thing is that any changes to the json and sql files should be removed. Those are auto-generated by the dotabase-builder project and will just get overridden next time dotabase gets generated.

**Comment by JustKappaMan** [comment]
@mdiller ok, done

**Pull request merged**
